services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "7000:7000"
    command: uvicorn main:app --host 0.0.0.0 --port 7000

  celery-worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: celery -A celery_app.celery_app:celery_app worker -l INFO

  celery-beat:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: celery -A celery_app.celery_app:celery_app beat -S redbeat.RedBeatScheduler -l INFO

